export { default as HomePage } from "./homepage/homepage-page";
export { default as AboutMePage } from "./about-me/about-me-page";
export { default as WebProjectsPage } from "./web/web-projects-page";
export { default as GameProjectsPage } from "./game/game-projects-page";
export { default as MobileProjectsPage } from "./mobile/mobile-projects-page";
export { default as GameProjectDetailPage } from "./game/project-detail/game-project-detail-page";
export { default as MobileProjectDetailPage } from "./mobile/project-detail/mobile-project-detail-page";
export { default as WebProjectDetailPage } from "./web/project-detail/web-project-detail-page";
export { default as Layout } from "./layout/layout";
